{
 "title": "TV Dashboard 1",
 "tags": [ "vmware" ],
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Eway - Homepage",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 0 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eww_stats",
     "query": "SELECT mean(\"time_total\") FROM \"eww_stats\" WHERE (\"name\" =~ /^cqcanj.*$/ AND \"page\" = 'homepage') AND $timeFilter GROUP BY time($__interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "time_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^cqcanj.*$/" },
      { "condition": "AND", "key": "page", "operator": "=", "value": "homepage" }
     ]
    }
   ]
  },
  {
   "title": "Top VM Disk Throughput",
   "type": "table",
   "gridPos": { "h": 9, "w": 8, "x": 16, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"virtualdisk_read_average\") AS \"read\", last(\"virtualdisk_write_average\") AS \"write\",last(\"virtualdisk_read_average\") + last(\"virtualdisk_write_average\") AS \"total\" FROM \"virtualmachine\"  WHERE time >= now() - 2m GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eway - Cart",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 6 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eww_stats",
     "select": [
      [
       { "params": [ "time_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^cqcanj.*$/" },
      { "condition": "AND", "key": "page", "operator": "=", "value": "cart" }
     ]
    }
   ]
  },
  {
   "title": "Disk space",
   "type": "table",
   "gridPos": { "h": 7, "w": 8, "x": 16, "y": 9 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "vm_disk_space",
     "select": [
      [
       { "params": [ "CapacityGB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "CapacityGB" ], "type": "alias" }
      ],
      [
       { "params": [ "FreeGB" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FreeGB" ], "type": "alias" }
      ],
      [
       { "params": [ "FreePercent" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "FreePercent" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Eway - Recommendations",
   "type": "flant-statusmap-panel",
   "gridPos": { "h": 6, "w": 16, "x": 0, "y": 12 },
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "eww_stats",
     "select": [
      [
       { "params": [ "time_total" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^cqcanj.*$/" },
      { "condition": "AND", "key": "page", "operator": "=", "value": "recommendations" }
     ]
    }
   ]
  },
  {
   "title": "Top VM CPU/Memory Usage",
   "type": "table",
   "gridPos": { "h": 10, "w": 8, "x": 16, "y": 16 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "cpu_usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 100" ], "type": "math" },
       { "params": [ "cpu-usage" ], "type": "alias" }
      ],
      [
       { "params": [ "cpu_usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000*1000" ], "type": "math" },
       { "params": [ "cpu-usagemhz" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_active_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "mem" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Storage stats per cluster",
   "type": "table",
   "gridPos": { "h": 8, "w": 10, "x": 0, "y": 18 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "select sum(\"read\") as \"Read Rate\", sum(\"write\") as \"Write Rate\", max(\"read_latency\") as \"Read Lat\", max(\"write_latency\") as \"Write Lat\" from (select last(storageadapter_read_average) as \"read\", last(storageadapter_write_average) as \"write\", last(storageadapter_totalreadlatency_average) as \"read_latency\", last(storageadapter_totalwritelatency_average) as \"write_latency\" from \"storageadapter\" where \"cluster\" != '' and \"instance\" != 'vmhba32' group by \"instance\",\"name\") group by \"cluster\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  { "type": "grafana-clock-panel", "gridPos": { "h": 2, "w": 6, "x": 10, "y": 18 } },
  {
   "title": "VSAN Boucherville & ColoD Ambiant Temperature",
   "type": "graph",
   "gridPos": { "h": 6, "w": 6, "x": 10, "y": 20 },
   "yaxes": [
    { "format": "celsius" }
   ],
   "targets": [
    {
     "alias": "$tag_server",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "server" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "ipmi_sensor",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=", "value": "01-inlet_ambient" },
      { "condition": "AND", "key": "server", "operator": "=~", "value": "/ilo-cqc(bou|anj).*/" }
     ]
    }
   ]
  }
 ]
}