{
 "title": "VMware - Performance by VMs",
 "tags": [ "vmware" ],
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "vmname",
    "label": "Virtual Machine",
    "query": "SHOW TAG VALUES FROM \"virtualmachine\" WITH KEY = \"name\" where \"host\" =~ /vcenter01/"
   },
   {
    "name": "Hosts",
    "query": "SHOW TAG VALUES FROM \"hostsystem\" WITH KEY = \"name\""
   }
  ]
 },
 "panels": [
  { "title": "General Performance", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "CPU Usage %",
   "type": "graph",
   "description": "CPU usage as a percentage during the interval.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 1 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"cpu_usage_average\")  / 100 FROM \"virtualmachine\" WHERE \"name\" =~ /^$vmname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "cpu_usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (Mhz)",
   "type": "graph",
   "description": "CPU usage as Hertz during the interval.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 1 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT mean(\"cpu_usage_average\")  / 100 FROM \"virtualmachine\" WHERE \"name\" =~ /^$vmname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "cpu_usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ "*1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Usage %",
   "type": "graph",
   "description": "Memory usage as percentage of total configured or available memory.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "mem_usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Active (GB)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "mem_active_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Swap In Rate",
   "type": "graph",
   "description": "Rate at which memory is swapped from disk into active memory during the interval.",
   "gridPos": { "h": 5, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "mem_swapinrate_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Swap Out Rate",
   "type": "graph",
   "description": "Rate at which memory is being swapped from active memory to disk during the current interval.",
   "gridPos": { "h": 5, "w": 8, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "mem_swapoutrate_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Overhead",
   "type": "graph",
   "description": "Amount of machine memory used by the VMkernel to run the virtual machine.",
   "gridPos": { "h": 5, "w": 8, "x": 16, "y": 15 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "mem_overhead_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Uptime",
   "type": "table",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 20 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "sys_uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Ready (ms)",
   "type": "graph",
   "description": "Time that the virtual machine was ready, but could not get scheduled to run on the physical CPU during last measurement interval.",
   "gridPos": { "h": 5, "w": 9, "x": 5, "y": 20 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "cpu_ready_summation" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Readiness (%)",
   "type": "graph",
   "description": "Percent of time the virtual machine is unable to run because it is contending for access to the physical CPU(s).",
   "gridPos": { "h": 5, "w": 10, "x": 14, "y": 20 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "cpu_readiness_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  { "title": "DISK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 25 } },
  {
   "title": "Disk Read Latency",
   "type": "graph",
   "description": "Average amount of time for a read operation from the virtual disk. Total latency = kernel latency + device latency.",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualdisk",
     "select": [
      [
       {
        "params": [
         "virtualdisk_totalreadlatency_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write Latency",
   "type": "graph",
   "description": "The average time a write to the virtual disk takes",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualdisk",
     "select": [
      [
       {
        "params": [
         "virtualdisk_totalwritelatency_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read IOPS",
   "type": "graph",
   "description": "Average number of read commands issued per second to the virtual disk during the collection interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       {
        "params": [
         "disk_numberreadaveraged_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write IOPS",
   "type": "graph",
   "description": "Average number of write commands issued per second to the virtual disk during the collection interval",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "disk",
     "select": [
      [
       {
        "params": [
         "disk_numberwriteaveraged_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read Throughput",
   "type": "graph",
   "description": "Rate of reading data from the virtual disk",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 40 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualdisk",
     "select": [
      [
       { "params": [ "virtualdisk_read_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write Throughput",
   "type": "graph",
   "description": "Rate of writing data to the virtual disk",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 40 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualdisk",
     "query": "SELECT SUM(\"virtualdisk_numberwriteaveraged_average\")  FROM \"virtualdisk\" WHERE \"name\" =~ /^$vmname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "virtualdisk_write_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Read Outstanding I/O",
   "type": "graph",
   "description": "Average number of outstanding read requests to the virtual disk during the collection interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualdisk",
     "query": "SELECT SUM(\"virtualdisk_numberwriteaveraged_average\")  FROM \"virtualdisk\" WHERE \"name\" =~ /^$vmname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "virtualdisk_readoio_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Disk Write Outstanding I/O",
   "type": "graph",
   "description": "Average number of outstanding write requests to the virtual disk during the collection interval.",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 47 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualdisk",
     "query": "SELECT SUM(\"virtualdisk_numberwriteaveraged_average\")  FROM \"virtualdisk\" WHERE \"name\" =~ /^$vmname$/ AND $timeFilter GROUP BY time($interval), \"name\" fill(null)",
     "select": [
      [
       { "params": [ "virtualdisk_writeoio_latest" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  { "title": "NETWORK", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 54 } },
  {
   "title": "Network Receive Rate (RX)",
   "type": "graph",
   "description": "Average rate at which data was received during the interval",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Network Transmit Rate (TX)",
   "type": "graph",
   "description": "Average rate at which data was transmitted during the interval",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 55 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "virtualmachine",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" },
      { "condition": "OR", "key": "esx", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  { "title": "OTHER", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 62 } },
  {
   "title": "Disk Free Space",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 63 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name [ $tag_disk ]",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "disk" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vm_disk_space",
     "select": [
      [
       { "params": [ "FreeGB" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$vmname$/" }
     ]
    }
   ]
  }
 ]
}