{
 "title": "VMware - Performance by Hosts",
 "tags": [ "vmware" ],
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "Hosts",
    "query": "SHOW TAG VALUES FROM \"hostsystem\" WITH KEY IN (\"name\")"
   }
  ]
 },
 "panels": [
  {
   "title": "Current VM CPU/Memory Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 7, "x": 0, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT last(\"cpu_usagemhz_average\") *1000*1000 AS \"cpu\", last(\"mem_active_average\") AS \"mem\" FROM \"virtualmachine\" WHERE (\"time\" >= now()-2m) AND (\"esx\" =~ /^$Hosts$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "cpu_usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "*1000*1000" ], "type": "math" },
       { "params": [ "cpu" ], "type": "alias" }
      ],
      [
       { "params": [ "mem_active_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "mem" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster CPU Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 0 },
   "format": "hertz",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hostsystem",
     "select": [
      [
       { "params": [ "cpu_usagemhz_average" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " *1000*1000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Cluster Power Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 0 },
   "format": "watt",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hostsystem",
     "select": [
      [
       { "params": [ "power_capacity_usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Disk Usage",
   "type": "table",
   "gridPos": { "h": 9, "w": 9, "x": 15, "y": 0 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "query": "SELECT last(\"virtualdisk_read_average\") AS \"read\", last(\"virtualdisk_write_average\") AS \"write\",last(\"virtualdisk_read_average\") + last(\"virtualdisk_write_average\") AS \"total\" FROM \"virtualmachine\" WHERE (time >= now() - 2m) AND (\"esx\" =~ /^$Hosts$/) GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "value" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Disk Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "storageadapter",
     "select": [
      [
       {
        "params": [
         "storageadapter_totalreadlatency_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "<>", "value": "vmhba32" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Throughput (Read)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 3 },
   "format": "MBs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "storageadapter",
     "select": [
      [
       { "params": [ "storageadapter_read_average" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "<>", "value": "vmhba32" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Avg Disk Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 7, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "storageadapter",
     "select": [
      [
       {
        "params": [
         "storageadapter_totalwritelatency_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "<>", "value": "vmhba32" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Throughput (Write)",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 11, "y": 6 },
   "format": "MBs",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "storageadapter",
     "select": [
      [
       { "params": [ "storageadapter_write_average" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " / 1024" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "<>", "value": "vmhba32" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Memory Capacity",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 0, "y": 9 },
   "format": "decmbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "hostsystem",
     "query": "SELECT sum(\"mem_capacity_provisioned_average\") FROM \"hostsystem\" WHERE (\"cluster\" =~ /^$cluster$/)",
     "select": [
      [
       { "params": [ "mem_totalcapacity_average" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Memory Usage (by Hosts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 4, "y": 9 },
   "yaxes": [
    { "format": "deckbytes" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hostsystem",
     "select": [
      [
       { "params": [ "mem_active_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "CPU Usage (by Hosts)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 10, "x": 14, "y": 9 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "hostsystem",
     "select": [
      [
       { "params": [ "cpu_usage_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 100" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Memory Consumed",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 11 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "hostsystem",
     "query": "SELECT sum(\"mem_capacity_provisioned_average\") FROM \"hostsystem\" WHERE (\"cluster\" =~ /^$cluster$/)",
     "select": [
      [
       { "params": [ "mem_consumed_average" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Active Memory Usage",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 14 },
   "format": "deckbytes",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "1m" ], "type": "time" }
     ],
     "measurement": "hostsystem",
     "select": [
      [
       { "params": [ "mem_active_average" ], "type": "field" },
       {
        "params": [],
        "type": "sum"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Adapter Throughput (READ)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storageadapter",
     "select": [
      [
       { "params": [ "storageadapter_read_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "!=", "value": "vmhba32" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Storage Adapter Throughput (WRITE)",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 24 },
   "yaxes": [
    { "format": "KBs" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storageadapter",
     "select": [
      [
       { "params": [ "storageadapter_write_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "!=", "value": "vmhba32" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Hosts Network Throughput (RX)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 31 },
   "yaxes": [
    { "format": "KBs", "label": "RX" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "net_received_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Hosts Network Throughput (TX)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 31 },
   "yaxes": [
    { "format": "KBs", "label": "TX" }
   ],
   "targets": [
    {
     "alias": "$tag_name ($tag_instance)",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "instance" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "net",
     "select": [
      [
       { "params": [ "net_transmitted_average" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Total Disk Latency per Host",
   "type": "graph",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$tag_name",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "name" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "storageadapter",
     "select": [
      [
       {
        "params": [
         "storageadapter_totalreadlatency_average"
        ],
        "type": "field"
       },
       {
        "params": [],
        "type": "sum"
       },
       { "params": [ " /$__interval_ms*60000" ], "type": "math" }
      ]
     ],
     "tags": [
      { "key": "instance", "operator": "<>", "value": "vmhba32" },
      { "condition": "AND", "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "Hosts Uptime",
   "type": "table",
   "gridPos": { "h": 15, "w": 5, "x": 11, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "hostsystem",
     "select": [
      [
       { "params": [ "sys_uptime_latest" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "uptime" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "name", "operator": "=~", "value": "/^$Hosts$/" }
     ]
    }
   ]
  },
  {
   "title": "VM Network Usage",
   "type": "table",
   "gridPos": { "h": 15, "w": 8, "x": 16, "y": 37 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "name" ], "type": "tag" }
     ],
     "measurement": "virtualmachine",
     "query": "SELECT last(\"net_bytesrx_average\") AS \"rx\", last(\"net_bytestx_average\") AS \"tx\", max(\"net_bytesrx_average\") AS \"rx_max\", max(\"net_bytestx_average\") AS \"tx_max\" FROM \"virtualmachine\" WHERE (\"esx\" =~ /^$Hosts$/) AND $timeFilter GROUP BY \"name\"",
     "select": [
      [
       { "params": [ "net_bytesrx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "rx" ], "type": "alias" }
      ],
      [
       { "params": [ "net_bytestx_average" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "tx" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "cluster", "operator": "=~", "value": "/^$cluster$/" }
     ]
    }
   ]
  }
 ]
}