{
 "title": "VSAN Overview",
 "tags": [
  "vsan",
  "vmware"
 ],
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5m",
 "panels": [
  {
   "title": "Total Capacity",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 0, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_capacity_global",
     "select": [
      [
       { "params": [ "totalCapacityB" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Freespace",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 3, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "datastore",
     "select": [
      [
       { "params": [ "free_space" ], "type": "field" }
      ]
     ],
     "tags": [
      { "key": "ds_name", "operator": "=", "value": "vsanDatastore" }
     ]
    }
   ]
  },
  {
   "title": "Virtual disks",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 6, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_capacity_vdisk",
     "select": [
      [
       { "params": [ "usedB" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "VM home objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 9, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_capacity_namespace",
     "select": [
      [
       { "params": [ "usedB" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "StatsDB objects",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 12, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_capacity_statsdb",
     "select": [
      [
       { "params": [ "usedB" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "File system overhead",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 15, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_capacity_fileSystemOverhead",
     "select": [
      [
       { "params": [ "usedB" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Checksum overhead",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 18, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_capacity_checksumOverhead",
     "select": [
      [
       { "params": [ "usedB" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Other",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 21, "y": 0 },
   "format": "bytes",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_capacity_other",
     "select": [
      [
       { "params": [ "usedB" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend Read IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "iopsRead" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend  Read Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 3 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "throughputRead" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "latencyAvgRead" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend Read Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 3 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "latencyAvgRead" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend Congestions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "congestion" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend OIO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 17, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "oio" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend OIO",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 20, "y": 3 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "oio" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend Write IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "iopsWrite" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend Write Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 6 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "throughputWrite" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Frontend Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 8, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "latencyAvgWrite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "/1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend Write Latency",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 11, "y": 6 },
   "format": "ms",
   "valueName": "current",
   "targets": [
    {
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "latencyAvgWrite" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ " / 1000" ], "type": "math" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend Congestions",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 3, "x": 14, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "congestion" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ]
    }
   ]
  },
  {
   "title": "Read Cache Hit Rate",
   "type": "table",
   "gridPos": { "h": 15, "w": 7, "x": 17, "y": 6 },
   "targets": [
    {
     "groupBy": [
      { "params": [ "uuid" ], "type": "tag" }
     ],
     "measurement": "vsanmetrics_disk-group",
     "select": [
      [
       { "params": [ "rcHitRate" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      {
       "key": "uuid",
       "operator": "<>",
       "value": "520f22be-9f71-8b91-421b-d87188544471"
      }
     ]
    }
   ]
  },
  {
   "title": "Backend Read IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 9 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "iopsRead" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend Read Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 9 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "throughputRead" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Frontend Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 9 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "latencyAvgRead" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "latencyAvgWrite" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend Write IOPS",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 12 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "iopsWrite" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Backend Write Throughput",
   "type": "singlestat",
   "gridPos": { "h": 3, "w": 4, "x": 4, "y": 12 },
   "format": "Bps",
   "valueName": "current",
   "targets": [
    {
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "throughputWrite" ], "type": "field" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Frontend Outstanding IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 8, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsanmetrics_cluster-domclient",
     "select": [
      [
       { "params": [ "oio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       },
       { "params": [ "Outstanding IO" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "Cluster Backend Latency",
   "type": "graph",
   "gridPos": { "h": 6, "w": 9, "x": 8, "y": 15 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "alias": "$col",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" }
     ],
     "measurement": "vsanmetrics_cluster-domcompmgr",
     "select": [
      [
       { "params": [ "latencyAvgRead" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Read" ], "type": "alias" }
      ],
      [
       { "params": [ "latencyAvgWrite" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       },
       { "params": [ " / 1000" ], "type": "math" },
       { "params": [ "Write" ], "type": "alias" }
      ]
     ]
    }
   ]
  },
  {
   "title": "vSAN VMkernel Throughput Inbound",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "RX" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsanmetrics_vsan-pnic-net",
     "select": [
      [
       { "params": [ "rxThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Inbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "<>", "value": "conmis1evpvsan1.staplesams.com" }
     ]
    }
   ]
  },
  {
   "title": "vSAN VMkernel Throughput Outbound",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "Bps", "label": "TX" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsanmetrics_vsan-pnic-net",
     "select": [
      [
       { "params": [ "txThroughput" ], "type": "field" },
       {
        "params": [],
        "type": "max"
       },
       { "params": [ "Outbound" ], "type": "alias" }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "<>", "value": "conmis1evpvsan1.staplesams.com" }
     ]
    }
   ]
  },
  {
   "title": "Hosts Frontend Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsanmetrics_host-domclient",
     "select": [
      [
       { "params": [ "iopsRead" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "<>", "value": "conmis1evpvsan1.staplesams.com" }
     ]
    }
   ]
  },
  {
   "title": "Hosts Frontend Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 27 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsanmetrics_host-domclient",
     "select": [
      [
       { "params": [ "iopsWrite" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "<>", "value": "conmis1evpvsan1.staplesams.com" }
     ]
    }
   ]
  },
  {
   "title": "Hosts Backend Read IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsanmetrics_host-domcompmgr",
     "select": [
      [
       { "params": [ "iopsRead" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "<>", "value": "conmis1evpvsan1.staplesams.com" }
     ]
    }
   ]
  },
  {
   "title": "Hosts Backend Write IOPS",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 33 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsanmetrics_host-domcompmgr",
     "select": [
      [
       { "params": [ "iopsWrite" ], "type": "field" },
       {
        "params": [],
        "type": "mean"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "<>", "value": "conmis1evpvsan1.staplesams.com" }
     ]
    }
   ]
  },
  {
   "title": "Hosts Frontend Outstanding IO",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 39 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "$tag_hostname",
     "groupBy": [
      { "params": [ "$__interval" ], "type": "time" },
      { "params": [ "hostname" ], "type": "tag" },
      { "params": [ "null" ], "type": "fill" }
     ],
     "measurement": "vsanmetrics_host-domclient",
     "select": [
      [
       { "params": [ "oio" ], "type": "field" },
       {
        "params": [],
        "type": "last"
       }
      ]
     ],
     "tags": [
      { "key": "hostname", "operator": "<>", "value": "conmis1evpvsan1.staplesams.com" }
     ]
    }
   ]
  }
 ]
}